from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    Float,
    Boolean,
    DateTime,
)
from datetime import datetime

from database import Base


# ============================================================
# JOB
# ============================================================

class Job(Base):
    """
    Stores normalized job-board records.

    Supports:
    - Job search
    - Source filtering
    - AI classification
    - AI skill/tag filtering
    - Recommendation scoring
    - Job assistant analysis
    - Duplicate detection
    """

    __tablename__ = "jobs"

    # ========================================================
    # PRIMARY IDENTIFICATION
    # ========================================================

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    job_id = Column(
        String(255),
        unique=True,
        index=True,
        nullable=False,
    )

    # ========================================================
    # CORE JOB INFORMATION
    # ========================================================

    title = Column(
        String(500),
        index=True,
        nullable=False,
    )

    company_name = Column(
        String(500),
        index=True,
        nullable=True,
    )

    location = Column(
        String(500),
        index=True,
        nullable=True,
    )

    source = Column(
        String(100),
        index=True,
        nullable=True,
    )

    # ========================================================
    # JOB DESCRIPTION
    # ========================================================

    description = Column(
        Text,
        nullable=True,
    )

    formatted_description = Column(
        Text,
        nullable=True,
    )

    # Original / normalized skills from dataset
    skills = Column(
        Text,
        nullable=True,
    )

    # ========================================================
    # EXPERIENCE
    # ========================================================

    min_experience = Column(
        Float,
        nullable=True,
    )

    max_experience = Column(
        Float,
        nullable=True,
    )

    # ========================================================
    # JOB METADATA
    # ========================================================

    employment_type = Column(
        String(100),
        nullable=True,
        index=True,
    )

    domain = Column(
        String(200),
        nullable=True,
        index=True,
    )

    apply_url = Column(
        Text,
        nullable=True,
    )

    posted_at = Column(
        String(100),
        nullable=True,
    )

    # ========================================================
    # DUPLICATE DETECTION
    # ========================================================

    duplicate_key = Column(
        String(1000),
        unique=True,
        index=True,
        nullable=True,
    )

    # ========================================================
    # AI JOB CLASSIFICATION
    # ========================================================
    #
    # These fields are generated by the AI classification
    # pipeline and stored as JSON strings inside SQLite Text
    # columns.
    #
    # Example:
    # ai_skills = ["python", "sql", "machine learning"]
    #
    # ========================================================

    ai_skills = Column(
        Text,
        nullable=True,
    )

    role_category = Column(
        String(200),
        nullable=True,
        index=True,
    )

    technical_keywords = Column(
        Text,
        nullable=True,
    )

    experience_level = Column(
        String(100),
        nullable=True,
        index=True,
    )

    min_experience_years = Column(
        Float,
        nullable=True,
    )

    max_experience_years = Column(
        Float,
        nullable=True,
    )

    ai_tags = Column(
        Text,
        nullable=True,
    )

    ai_processed = Column(
        Boolean,
        default=False,
        nullable=False,
        index=True,
    )


# ============================================================
# USER PROFILE
# ============================================================

class UserProfile(Base):
    """
    Stores the user's resume-derived profile.

    The profile is intentionally separated from the Job table.

    It powers:
    - Resume upload
    - Resume parsing
    - Personalized recommendations
    - "Recommended for You"
    - Job suitability analysis
    - Missing-skill analysis
    - AI assistant personalization

    Lists are stored as JSON strings in SQLite Text columns.
    """

    __tablename__ = "user_profiles"

    # ========================================================
    # PRIMARY IDENTIFICATION
    # ========================================================

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    # Prototype-friendly profile identifier.
    # This allows us to support multiple profiles later
    # without introducing a complete authentication system.
    profile_id = Column(
        String(255),
        unique=True,
        index=True,
        nullable=False,
    )

    # ========================================================
    # RESUME INFORMATION
    # ========================================================

    resume_filename = Column(
        String(500),
        nullable=True,
    )

    resume_text = Column(
        Text,
        nullable=True,
    )

    # ========================================================
    # PARSED PROFILE
    # ========================================================

    profile_summary = Column(
        Text,
        nullable=True,
    )

    skills = Column(
        Text,
        nullable=True,
    )

    technologies = Column(
        Text,
        nullable=True,
    )

    experience = Column(
        Text,
        nullable=True,
    )

    education = Column(
        Text,
        nullable=True,
    )

    certifications = Column(
        Text,
        nullable=True,
    )

    # ========================================================
    # CAREER PREFERENCES
    # ========================================================

    preferred_roles = Column(
        Text,
        nullable=True,
    )

    preferred_locations = Column(
        Text,
        nullable=True,
    )

    preferred_domains = Column(
        Text,
        nullable=True,
    )

    preferred_employment_types = Column(
        Text,
        nullable=True,
    )

    # ========================================================
    # PROFILE EXPERIENCE SIGNALS
    # ========================================================

    experience_level = Column(
        String(100),
        nullable=True,
        index=True,
    )

    total_experience_years = Column(
        Float,
        nullable=True,
    )

    # ========================================================
    # AI / RESUME PROCESSING STATUS
    # ========================================================

    ai_processed = Column(
        Boolean,
        default=False,
        nullable=False,
        index=True,
    )

    parsing_error = Column(
        Text,
        nullable=True,
    )

    # ========================================================
    # TIMESTAMPS
    # ========================================================

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )


# ============================================================
# RESUME JOB MATCH
# ============================================================

class ResumeJobMatch(Base):
    """
    Stores calculated resume-to-job recommendation results.

    This makes the recommendation system extensible and allows
    us to expose understandable match information to the UI.

    Example:

        Overall Match: 87%

        Matched Skills:
            Python
            SQL
            Machine Learning

        Missing Skills:
            Docker
            AWS

        Reasons:
            Strong technical skill overlap
            Relevant role
            Relevant experience level
    """

    __tablename__ = "resume_job_matches"

    # ========================================================
    # PRIMARY IDENTIFICATION
    # ========================================================

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    profile_id = Column(
        String(255),
        index=True,
        nullable=False,
    )

    job_id = Column(
        String(255),
        index=True,
        nullable=False,
    )

    # ========================================================
    # MATCH SCORE
    # ========================================================

    match_score = Column(
        Float,
        nullable=False,
        default=0.0,
    )

    # ========================================================
    # MATCH BREAKDOWN
    # ========================================================

    skill_score = Column(
        Float,
        nullable=True,
    )

    role_score = Column(
        Float,
        nullable=True,
    )

    experience_score = Column(
        Float,
        nullable=True,
    )

    location_score = Column(
        Float,
        nullable=True,
    )

    domain_score = Column(
        Float,
        nullable=True,
    )

    keyword_score = Column(
        Float,
        nullable=True,
    )

    # ========================================================
    # EXPLAINABLE RECOMMENDATION DATA
    # ========================================================
    #
    # Stored as JSON strings.
    #
    # matched_skills:
    # ["python", "sql", "machine learning"]
    #
    # missing_skills:
    # ["docker", "aws"]
    #
    # reasons:
    # ["Strong skill match", "Relevant role"]
    #
    # ========================================================

    matched_skills = Column(
        Text,
        nullable=True,
    )

    missing_skills = Column(
        Text,
        nullable=True,
    )

    reasons = Column(
        Text,
        nullable=True,
    )

    # ========================================================
    # TIMESTAMP
    # ========================================================

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )


# ============================================================
# ASSISTANT CONVERSATION
# ============================================================

class AssistantConversation(Base):
    """
    Stores lightweight assistant conversation history.

    IMPORTANT:
    Gemini API keys are NEVER stored here.

    The frontend provides the user's API key when invoking
    the assistant. The backend uses it for the request and
    does not persist it.

    Conversation history can be used for:
    - Follow-up questions
    - Job comparison
    - Resume improvement
    - Preparation guidance
    - Personalized job discussions
    """

    __tablename__ = "assistant_conversations"

    # ========================================================
    # PRIMARY IDENTIFICATION
    # ========================================================

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    conversation_id = Column(
        String(255),
        index=True,
        nullable=False,
    )

    profile_id = Column(
        String(255),
        index=True,
        nullable=True,
    )

    # ========================================================
    # MESSAGE
    # ========================================================

    role = Column(
        String(50),
        nullable=False,
    )

    message = Column(
        Text,
        nullable=False,
    )

    # ========================================================
    # OPTIONAL JOB CONTEXT
    # ========================================================

    job_id = Column(
        String(255),
        nullable=True,
        index=True,
    )

    # ========================================================
    # TIMESTAMP
    # ========================================================

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

